import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './Componentes/Nav'
import Footer from './Componentes/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sitio next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
